### ISSUE TITLE
apt-buildpack https support (apt-transport-https)

### ISSUE THREAD

**Issue by lrstanley** [cloudfoundry/apt-buildpack#20] opened 2019-04-29 15:09 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`? cf-cli: **v6.43.0** and cf version: **2.2.9-build.5** and tested with **2.3.8-build.6**.

What version of the buildpack you are using? v0.1.6

If you were attempting to accomplish a task, what was it you were attempting to do? use an Artifactory based Ubuntu repository, as we are unable to access ubuntu repos directly due to corporate firewall reasons.

What did you expect to happen? It to fetch packages from Artifactory as if it were fetching from Ubuntu directly.

What was the actual behavior? Our Artifactory cluster is https only, which requires the https module for apt. I believe it is failing out because the buildpack doesn't have the https module.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

Deploy logs:

```
Creating app python-example...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 13.09 KiB / 13.09 KiB  100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Downloading python_buildpack...
   Downloading apt_buildpack...
   Downloaded python_buildpack
   Downloaded apt_buildpack
   Cell e4b900e7-e937-48e0-b4eb-3332195c51c6 creating container for instance dc9f2501-88e5-46fa-9e9f-07e0d4431c02
   Cell e4b900e7-e937-48e0-b4eb-3332195c51c6 successfully created container for instance dc9f2501-88e5-46fa-9e9f-07e0d4431c02
   Downloading app package...
   Downloaded app package (13.1K)
   -----> Apt Buildpack version 0.1.6
          **WARNING** 
          ⚠️️️ 🚨️️ ⚠️ 🚨️️
          This application is being deployed on cflinuxfs2 which is being deprecated in April, 2019.
          Please migrate this application to cflinuxfs3.
          For more information about changing the stack, see https://docs.cloudfoundry.org/devguide/deploy-apps/stacks.html
          ⚠️️️ 🚨️️ ⚠️ 🚨️️
   -----> Adding apt repos
   -----> Updating apt cache
   E: The method driver /usr/lib/apt/methods/https could not be found.
          **ERROR** Error running supply: failed to apt-get update 
          
          exit status 100
   Failed to run all supply scripts: exit status 14
   Exit status 225
   Cell e4b900e7-e937-48e0-b4eb-3332195c51c6 stopping instance dc9f2501-88e5-46fa-9e9f-07e0d4431c02
   Cell e4b900e7-e937-48e0-b4eb-3332195c51c6 destroying container for instance dc9f2501-88e5-46fa-9e9f-07e0d4431c02
   Cell e4b900e7-e937-48e0-b4eb-3332195c51c6 successfully destroyed container for instance dc9f2501-88e5-46fa-9e9f-07e0d4431c02
Error staging application: Staging error: staging failed
FAILED
Deleting app python-example in org myorg / space myspace as myuser...
OK
Renaming app python-example-venerable to python-example in org myorg / space myspace as myuser...
OK
error running command: exit status 1
```

Repo:

1. `apt.yml`:
```
---
packages:
- tesseract-ocr
- libtesseract-dev
repos:
- deb https://myartifactory.domain.com/ubuntu-archive-remote bionic universe
```
2. deploy the app.

**Sidenote**: I also noticed that if I didn't specify Artifactory, because Ubuntu is blocked, it just succeeded, but didn't show it was installed when I logged into the container. I think this may be similar to https://github.com/cloudfoundry/apt-buildpack/issues/19

**Comment by kardolus** [comment] 2019-05-01 14:15
Thanks @lrstanley, 

Not sure if this is possible. To me it seems we would have to install the https module from a local deb package in order to make this work. But I'm not sure.

@sclevine ideas?

**Comment by shanks3012** [comment] 2019-05-06 19:38
Duplicate of: https://github.com/cloudfoundry/apt-buildpack/issues/9.

Please use cflinuxfs3 as cflinuxfs2 is no longer supported.

Thanks.

**Closed by shanks3012** 2019-05-06 19:38 UTC
Labels: scheduled

**Comment by lrstanley** [comment] 2019-05-07 12:39
Thanks, didn't notice that existing issue.
